version: '3.8'

services:
  menu_app:
    container_name: menu_app
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint: >
      sh -c "
         python main.py
      "
    ports:
      - "8000:8000"
    depends_on:
      db_pg:
        condition: service_started
  db_pg:
    image: postgres:15.1-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 223572
      POSTGRES_DB: postgres
    volumes:
      - ./data:/var/lib/postgresql/data
